import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import FlowbiteContext from "@/infra/contexts/FlowbiteContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} bg-gray-900 min-h-screen pb-4 flex flex-col`}
      >
        <Navbar />
        <FlowbiteContext>{children}</FlowbiteContext>
      </body>
    </html>
  );
}
